### 스칼라

In [1]:
# 스칼라의 정의
x = 2
print(x)
x = 3
print(x)
x = 2
y = 3
# 덧셈
z = x + y
print(z)
# 뺄셈
z = x - y
print(z)
# 곱셉
z = x * y
print(z)
# 나눗셈
z = x / y
print(z)

2
3
5
-1
6
0.6666666666666666


### 벡터

In [2]:
# 덧셈
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] + v[i]
    w.append(val)
print(w)

# 뺄셈
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] - v[i]
    w.append(val)
print(w)

# 곱셈(벡터 * 스칼라)
u = [2, 4, 3]
a = 3

n = len(u)
w = []

for i in range(0, n):
    val = a * u[i]
    w.append(val)
print(w)

# 곱셈(벡터 * 벡터)
u = [1, 2, 4]
a = [7, 3, 2]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] * a[i] 
    w.append(val)
print(w)

# 나눗셈
u = [1, 2, 4]
a = [7, 3, 2]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] / a[i] 
    w.append(val)
print(w)

[5, 7, 9]
[-3, -3, -3]
[6, 12, 9]
[7, 6, 8]
[0.14285714285714285, 0.6666666666666666, 2.0]


### 넘파이

In [3]:
import numpy as np

In [5]:
# 덧셈
u = np.array([1,2,3])
v = np.array([4,5,6])
w = u + v
print(w)
# 뺄셈
w = u - v
print(w)
# 곱셈(스칼라 * 벡터)
a = 3
w = a * u
print(w)
# 곱셈(벡터 * 벡터)
w = u * v
print(w)
# 나눗셈
w = u / v
print(w)

[5 7 9]
[-3 -3 -3]
[3 6 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


### 행렬

In [1]:
# 행렬의 덧셈
A = [[2, 7],[3, 4],[6, 1]]
B = [[1, 4], [4, -1], [2, 5]]

n= len(A)
p = len(A[0])
res = []

for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] + B[i][j]
        row.append(val)
    res.append(row)
print(res)

[[3, 11], [7, 3], [8, 6]]


In [3]:
# 행렬의 뺄셈
A = [[2, 7],[3, 4],[6, 1]]
B = [[1, 4], [4, -1], [2, 5]]

n= len(A)
p = len(A[0])
res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] - B[i][j]
        row.append(val)
    res.append(row)
print(res)

[[1, 3], [-1, 5], [4, -4]]


In [4]:
# 행렬의 스칼라 곱
A = [[2, 7],[3, 4],[6, 1]]
b = 2

n= len(A)
p = len(A[0])
res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        val = b * A[i][j]
        row.append(val)
    res.append(row)
print(res)

[[4, 14], [6, 8], [12, 2]]


In [5]:
# 행렬의 원소 곱
A = [[2, 7],[3, 4],[6, 1]]
B = [[1, 4], [4, -1], [2, 5]]

n= len(A)
p = len(A[0])
res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] * B[i][j]
        row.append(val)
    res.append(row)
print(res)

[[2, 28], [12, -4], [12, 5]]


In [8]:
# 행렬 곱
A = [[2, 7],[3, 4],[6, 1]] # 3 * 2
B = [[3, -3, 5], [-1, 2, -1]] # 2 * 3

n= len(A)
p1 = len(A[0])
p2 = len(B[0])
res = []
for i in range(0, n):
    row = []
    for j in range(0, p2):
        val = 0
        for k in range(0, p1):
            val += A[i][k] * B[k][j]
        row.append(val)
    res.append(row)
print(res)

[[-1, 8, 3], [5, -1, 11], [17, -16, 29]]
