## 4. 다양한 행렬
---
### 전치 행렬

In [2]:
A = [[1,5],[3,4],[6,2]]

n = len(A)
p = len(A[0])

At = []
for i in range(0, p):
    row = []
    for j in range(0, n):
        val = A[j][i]
        row.append(val)
    At.append(row)
print(At)

[[1, 3, 6], [5, 4, 2]]


### 넘파이 - 전치행렬

In [3]:
import numpy as np

In [11]:
A = np.array([[1,5],[3,4],[6,2]])
At = np.transpose(A)
print(At)
print("-------")
print(A.T)

[[1 3 6]
 [5 4 2]]
-------
[[1 3 6]
 [5 4 2]]


### 대칭 행렬

In [12]:
# 전치 행렬
def transpose(A):
    n = len(A)
    p = len(A[0])
    
    At = []
    for i in range(0, p):
        row = []
        for j in range(0, n):
            val = A[j][i]
            row.append(val)
        At.append(row)
    return At

In [6]:
# 행렬 곱을 구하는
def matmul(A, B):
    n = len(A)
    p1 = len(A[0])
    p2 = len(B[0])
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p2):
            val = 0
            for k in range(0, p1):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

In [14]:
A = [[1,0,2], [0,2,1], [2,1,1]]
At = transpose(A)
print(At)

[[1, 0, 2], [0, 2, 1], [2, 1, 1]]


In [15]:
A == At

True

In [16]:
AA = A
for i in range(0, 9):
    AA = matmul(AA, A)
    print("행렬 A의", i+2, "제곱은", AA)

행렬 A의 2 제곱은 [[5, 2, 4], [2, 5, 3], [4, 3, 6]]
행렬 A의 3 제곱은 [[13, 8, 16], [8, 13, 12], [16, 12, 17]]
행렬 A의 4 제곱은 [[45, 32, 50], [32, 38, 41], [50, 41, 61]]
행렬 A의 5 제곱은 [[145, 114, 172], [114, 117, 143], [172, 143, 202]]
행렬 A의 6 제곱은 [[489, 400, 576], [400, 377, 488], [576, 488, 689]]
행렬 A의 7 제곱은 [[1641, 1376, 1954], [1376, 1242, 1665], [1954, 1665, 2329]]
행렬 A의 8 제곱은 [[5549, 4706, 6612], [4706, 4149, 5659], [6612, 5659, 7902]]
행렬 A의 9 제곱은 [[18773, 16024, 22416], [16024, 13957, 19220], [22416, 19220, 26785]]
행렬 A의 10 제곱은 [[63605, 54464, 75986], [54464, 47134, 65225], [75986, 65225, 90837]]


In [17]:
A = [[1,0,3],[2,1,4],[0,1,1]]
At = transpose(A)
print(A)
print(At)

[[1, 0, 3], [2, 1, 4], [0, 1, 1]]
[[1, 2, 0], [0, 1, 1], [3, 4, 1]]


In [18]:
matmul(A, At)

[[10, 14, 3], [14, 21, 5], [3, 5, 2]]

In [19]:
matmul(At, A)

[[5, 2, 11], [2, 2, 5], [11, 5, 26]]

### 넘파이 - 대칭 행렬

In [20]:
import numpy as np

In [21]:
A = np.array([[1,0,2],[0,2,1],[2,1,1]])
print(A)

[[1 0 2]
 [0 2 1]
 [2 1 1]]


In [22]:
At = np.transpose(A)
print(At)

[[1 0 2]
 [0 2 1]
 [2 1 1]]


In [23]:
A == At

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
AA = A
for i in range(0,9):
    AA = np.matmul(AA, A)
    print("행렬 A의", i+2, "제곱은")
    print(AA)
    print("=====================")

행렬 A의 2 제곱은
[[5 2 4]
 [2 5 3]
 [4 3 6]]
행렬 A의 3 제곱은
[[13  8 16]
 [ 8 13 12]
 [16 12 17]]
행렬 A의 4 제곱은
[[45 32 50]
 [32 38 41]
 [50 41 61]]
행렬 A의 5 제곱은
[[145 114 172]
 [114 117 143]
 [172 143 202]]
행렬 A의 6 제곱은
[[489 400 576]
 [400 377 488]
 [576 488 689]]
행렬 A의 7 제곱은
[[1641 1376 1954]
 [1376 1242 1665]
 [1954 1665 2329]]
행렬 A의 8 제곱은
[[5549 4706 6612]
 [4706 4149 5659]
 [6612 5659 7902]]
행렬 A의 9 제곱은
[[18773 16024 22416]
 [16024 13957 19220]
 [22416 19220 26785]]
행렬 A의 10 제곱은
[[63605 54464 75986]
 [54464 47134 65225]
 [75986 65225 90837]]


In [26]:
A = np.array([[1,0,3],[2,1,4],[0,1,1]])
print(A)

[[1 0 3]
 [2 1 4]
 [0 1 1]]


In [27]:
At = A.T
print(At)

[[1 2 0]
 [0 1 1]
 [3 4 1]]


In [28]:
np.matmul(A, At)

array([[10, 14,  3],
       [14, 21,  5],
       [ 3,  5,  2]])

In [29]:
np.matmul(At, A)

array([[ 5,  2, 11],
       [ 2,  2,  5],
       [11,  5, 26]])

### 대각행렬

In [2]:
# 대각행렬 만들기
A = [[1,2,3],[4,5,6],[7,8,9]]

def diag(A):
    n = len(A)
    D = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(A[i][j])
            else:
                row.append(0)
        D.append(row)
    return D
print(diag(A))

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]


In [3]:
# 원소 주어지면 대각행렬 만들기
def ele2diag(a):
    n = len(a)
    D = []
    for i in range(0,n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(a[i])
            else:
                row.append(0)
        D.append(row)
    return D

In [8]:
# 일반 행렬에 대각 행렬을 곱했을 때
A = [[1,2,3],[4,5,6],[7,8,9]]
D = ele2diag([1,3,4])
print(A)
print(D)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 0, 0], [0, 3, 0], [0, 0, 4]]


In [9]:
AD = matmul(A, D)
print(AD)

[[1, 6, 12], [4, 15, 24], [7, 24, 36]]


In [10]:
DA = matmul(D, A)
print(DA)

[[1, 2, 3], [12, 15, 18], [28, 32, 36]]


### 넘파이 - 대각 행렬

In [12]:
import numpy as np

In [13]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.diag(A) # 대각 원소 구함
print(D) 

[1 5 9]


In [14]:
print(np.diag(D)) # 다시 넣으면 대각 행렬 구함

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [15]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.diag([1,3,4])
AD = np.matmul(A, D)
print(AD)

[[ 1  6 12]
 [ 4 15 24]
 [ 7 24 36]]


In [16]:
DA = np.matmul(D, A)
print(DA)

[[ 1  2  3]
 [12 15 18]
 [28 32 36]]
